[build]
  publish = "public"
  command = "npm run build"
  functions = "functions"
[template.environment]
  SENDGRID_API_KEY = "Your Sendgrid API Key (required for newsletter signup box)"
  SENDGRID_WELCOME_SENDER_EMAIL = "Sendgrid Welcome Sender Email"
  SENDGRID_WELCOME_SENDER_NAME = "Sendgrid Welcome Sender Name"
  SENDGRID_WELCOME_TEMPLATE_ID = "Sendgrid Welcome Email Template ID"