[build]
  publish = "public"
  command = "npm run build"
  functions = "functions"
[template.environment]
  SENDGRID_API_KEY = "Your Sendgrid API Key (required for newsletter signup box)"
  SENDGRID_LIST_IDS = "An array of List IDs to add the new address to (optional)"
